### ISSUE TITLE
1776: St. Paul's Chapel

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#14]
An important Broadway landmark, built in 1766 just north of Trinity Church, we need this chapel to make our 1776 level more accurate.  It's a higher priority because it's near the One World Trade Center.   A few details:

- Google Maps link: https://maps.app.goo.gl/FNCebTT339TqXzV8A
- Wikipedia: https://en.wikipedia.org/wiki/St._Paul%27s_Chapel

@KatherineMcDonnell - can you find images or descriptions of this chapel as it appeared in 1776?  I think it wouldn't be too different from the current design.  Please add any details here as comments in this Github issue

@tantayota - Alvin: can you build us this model?

![image](https://github.com/TimeWalkOrg/Manhattan/assets/694013/723e4547-0c30-4645-b4e5-369aab4b9880)

![image](https://github.com/TimeWalkOrg/Manhattan/assets/694013/e572887f-16ec-4aa7-a1ae-78682312b132)

**Comment by KatherineMcDonnell** [comment]
Estimated dimensions of the chapel via Ted's measurements:

76 feet x 135.5 feet

![Width of st pauls chapel](https://github.com/TimeWalkOrg/Manhattan/assets/160678867/29bfcf3e-f436-4982-8992-baf41813720e)
![st  paul's length](https://github.com/TimeWalkOrg/Manhattan/assets/160678867/ae42c03e-9542-47df-be66-0542a81eeea9)

The original chapel did not include the majority of the spire as it stands today, but the spire as it is today was built sometime between 1793 and 1796 --> could be good to have two different versions of the chapel incase we decide to make a level post 1776.

**Comment by tedbarnett** [comment]
Model looks great.  Waiting to see it in the final 1776 level (which @deedox is re-enabling) in issue #73

**Comment by tedbarnett** [comment]
![image](https://github.com/user-attachments/assets/a69ff0e6-dcd1-4bba-9b9e-f6a9b0984b75)

The blueprint is in the project, and looks great.  Just have to place it in world.
