### ISSUE TITLE
Fix "floating maps"

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#17]
When the maps appear, they seem to float about 20m above the terrain. Is there any way to set them all to Z=0 and yet make them visible through the terrain somehow?  Is there some magical shaded we could apply to the map objects that would ensure they are always visible even when behind/below the terrain?

Seems like having maps at Z=20 will lead to alignment errors when we try to sculpt the terrain, or (later) place buildings.

**Comment by deedox** [comment]
My suggestion would be to use the extra maps as a terrain texture which is projected to the heightmap. Some extra coding would be necessary to handle the foliage but I think it's doable..

**Comment by tedbarnett** [comment]
Looks like you did this!
