### ISSUE TITLE
Water and shoreline wave improvements

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#18]
Since 1609 is all about nature, it would be nice if the waves hitting the shore looked more "real".  Any way to make them more foamy or dramatic?

**Comment by deedox** [comment]
That could work, we can combine multiple ocean meshes with the water system.

**Comment by tedbarnett** [comment]
The shoreline for 1609, and the waves in the 1660 harbor look too synthetic.  

- Waves should crash with more spray on the rocks in 1609.  Water exiting creeks should look more real (turbulence?).
- Harbor waves in 1660 seem 2x too large, lack resolution, no riffles on the water (which I though we had working before)
