### ISSUE TITLE
Sounds: "Seasons" sounds

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#22]
Now that Dario has enabled us to switch seasons (Spring/Summer/Fall/Winter using numpad "+" and "-" keys), we need appropriate sounds (when in forests):
- Summer: Bird sounds?
- Fall: Leaves blowing?
- Winter: cold wind?
- Spring: more birds chirping?

It's possible some of these are already included with the weather assets Dario imported.

**Comment by tedbarnett** [comment]
@SunilPrabhuu Is this one working (in the new build)?  I can test it but not sure what I'm looking for. 

If not already enabled, can we implement this?

**Comment by SunilPrabhuu** [comment]
@tedbarnett I haven't downloaded the new build yet, but it was pushed to the old one. It's built into the DayNightCycle BP, and should automatically play and switch the seasonal sounds, with an attenuation that covers the full map.
