### ISSUE TITLE
East Village rivers are "dry" (terrain issue)

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#24]
In our 1660 scene, the landscape on the East Side of lower Manhattan seems to be too flat.  No rivers are visible.

![image](https://github.com/TimeWalkOrg/Manhattan/assets/694013/ac838ae2-8487-49ec-b8d2-ed918ab4b4b1)

**Comment by KatherineMcDonnell** [comment]
still an issue as of 5/14

**Comment by tedbarnett** [comment]
Still seems to be true


![Image](https://github.com/user-attachments/assets/441caf0a-cd72-4530-8e86-bd2fda6b95b5)
