### ISSUE TITLE
Set start position to Flying mode, floating above Governor's Island, facing North

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#24]
For demos of this project, I'd like to start with the camera position as in the image below. 
- I set the PlayerStart object to this location in the github project, but I don't know to start in "Fly" mode

![image](https://github.com/TimeWalkOrg/Manhattan/assets/694013/1c3333d8-cbfd-49f4-926b-50e75e026357)

**Comment by tedbarnett** [comment]
Can we also make sure that the project opens with the camera in this same position (instead of at the Collect Pond)?

**Comment by deedox** [comment]
The project opens where you have left and saved the scene..
