### ISSUE TITLE
Manually add 3rdPartyAssets folder to your project

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#25]
I purchased this 3D model of Henry Hudson's ship "Half Moon": https://www.turbosquid.com/3d-models/half-moon-galleon-ship-3ds/505643

This is the ship he arrived in on September 3, 1609.

I also bought a simple "campfire" asset to try adding some fires where the Lenape settlements once were.  Will look cool at night, and in the day if I can figure out how to make the smoke rise much higher!

Since I purchased these assets, we cannot leave them in our public Github project, so I added it to the .gitignore (which means it isn't uploaded to the public web-based github repository).  So I created a new folder inside Content called "3rdPartyAssets" and put both HalfMoon and the Campfire assets in that folder.  If you purchased any assets (the "BlackAlder"?) please move them into that folder too when you edit.

For you to also see it at your end, you will need to download the .zip file I sent you in Upwork messages, unzip that folder ("3rdPartyAssets"), and put it inside the "Content" folder in the project.  You should then see the HalfMoon appear here:

![image](https://github.com/TimeWalkOrg/Manhattan/assets/694013/fc533c1a-d84d-45d6-a43e-4fcd8bb185cb)

**Comment by tedbarnett** [comment]
Small note: the water around the boat seems too transparent.  I can easily see the whole rudder and bottom of the ship, which doesn't seem realistic.  Can we hide that part of the ship, or change the water transparency level?

**Comment by tedbarnett** [comment]
![image](https://github.com/TimeWalkOrg/Manhattan/assets/694013/c9f70a10-0330-429a-ba90-a15b4ccb0d83)

**Comment by tedbarnett** [comment]
And I'd like to animate the sails and boat movement soon

**Comment by deedox** [comment]
All of my content like BlackElder or KiteDemo is free. I will cleanup the folder structure as we progress..
