### ISSUE TITLE
Build camera-tracking "fly-through"

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#31]
I'd like to be able to make a better demo video of a "fly-through" of Manahatta.  Using my keyboard results in jerky movement.  Can we set up a spline and animate the camera running through the same path (start above Governor's Island, fly over Battery, land near Collect Pond, walk around, look up at trees)?

https://www.youtube.com/watch?v=UulpWHi2k4E

**Comment by deedox** [comment]
The link is not working...

**Comment by tedbarnett** [comment]
Nice!  Can you add "G: Generate fly-through" as a menu item too?
