### ISSUE TITLE
Tides

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#4]
As a TimeWalk engine component, it would be cool to enable a basic tide simulation for the ocean height. At the Battery (ie southern tip of Manhattan) the [tide varies by about 7 feet](https://www.usharbors.com/harbor/new-york/new-york-the-battery-ny/tides/) (2.1m).

This would look especially cool when users are holding the "time forward" key. The sun and moon move, and so would the tide. 

Possible?

**Comment by deedox** [comment]
That could work with animating the ocean's z axis.. I was also thinking on how we could implement seasons and weather, that could also be linked to the ocean system.

**Comment by tedbarnett** [comment]
Sounds like some people have struggled with changing water levels dynamically: https://www.reddit.com/r/unrealengine/comments/14c7b9n/ue5_rising_water_level_problem/

**Comment by tedbarnett** [comment]
TimeWalk should have the best possible sun, moon, sky, weather system available. As with tides, we should be able to roll time forward or backward seamlessly.  The sky changes, buildings come and go.  Events (animation or AI sequences) take place.
What do we have now and what can we build -- or buy from the Unreal Marketplace?
