### ISSUE TITLE
Add NPCs to harbor scene

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#57]
We need 5-10 NPCs at minimum. Ideally motion-captured animated 3D models.

**Comment by JustPineStudio** [comment]
We have a couple of Rokoko suits if we need some motion capture. Just let me know what kind of animations are we looking for.

**Comment by tedbarnett** [comment]
3 male merchants, 4 colonist women, 1 male child, 1 male soldier, 1 male farmer
