### ISSUE TITLE
Loading Screen Edits

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#65]
The new loading screen looks beautiful.  A few edits below.

![Image](https://github.com/user-attachments/assets/6c75c013-c530-4ea0-8bb2-e432e3859220)

- Remove the "New Amsterdam September 12..." text from top-right.  This should appear when in the loaded level, not on main menu.
- Buttons are 2x too large: Shrink the buttons to ~50% of current size
- Hide the level name text ("LvL1_LOAD_SCREEN")
- I think it looks better (and requires less scrolling) to have the vertical stack of the buttons as on the "T" screen before.  The buttons were designed to be wide for that reason.  Scrolling horizontally seems less efficient.  Is it required for VR maybe?
- The button image animation is cool, but seems to jump back to the zoomed-out view sometimes, at least on the 1609 button.  Feels better if it just zooms in and stays zoomed as long as you are hovering.
- A nit, but the date text on each button ("12000 BC", "1609") should be a little further away from the edges of the button (i.e. down-right 20 pixels or so)
- The blur/de-rez animation that occassionally runs on the TimeWalk logo is cool, but gets annoying and looks a bit like an actual glitch.  Replace with a sparkle or shine effect maybe?  Or do without?
- Seems okay to leave the non-functional buttons working and have clicks go nowhere (e.g. clicking on "VR") for now.  Will come up with content for those later.

**Comment by tedbarnett** [comment]
Looks good for now.  Will still want to improve button size (way too huge: can't see all the years available on one screen), and the fonts need work (only use Silenta for TimeWalk logo: Arial or other for body text).

Disabled "glitch" effect on logo.  Not necessary.

**Comment by deedox** [comment]
There are still some tweaks to do but most UI elements are working now.. Willl revert the other fonts to a more regular one..
