### ISSUE TITLE
1609: Floating trees (not on terrain)

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#66]
In 1609 (and 1660 too possibly), the trees all look odd.  Not quite attached to the ground for one thing.  And are the trunks longer somehow?

![image](https://github.com/user-attachments/assets/347c617b-9d6b-4b62-89c3-89dc68521cad)

**Comment by tedbarnett** [comment]
Still visible.  Did adjustments to terrain require we re-run some PCG process?

![Image](https://github.com/user-attachments/assets/5a4bac71-bcc2-478a-861b-cd90ec60bed2)

**Comment by tedbarnett** [comment]
Still seeing them in 1609 (as of August 2, 2024)

![Screenshot 2024-08-02 161050](https://github.com/user-attachments/assets/9fc3b5c1-7e10-4dfa-bd2b-6e2e28d59ba5)

**Comment by tedbarnett** [comment]
Still happening.  Also: creek edges look too "straight" and artificial.  Any way to blend them in better?

![Image](https://github.com/user-attachments/assets/6129ddb5-900e-489d-ba5a-424f564d53ce)

**Comment by deedox** [comment]
The issue is related to the PCG graph and their placement..The creek is missing the virtual texture for the blending and also the PCG vegetation which also has to be fixed.  I will check that today.
