### ISSUE TITLE
1660: Complete Gardens, Crops, Orchards, Flowers

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#7]
Per the Castello Plan: ensure there are trees, bushes, gardens wherever indicated

Use PCG where it works but hand-place plants if more accurate.

**Comment by KatherineMcDonnell** [comment]
A few gardens are in the northwest corner, but some still need to be added to the rest of the map in 1660

**Comment by tedbarnett** [comment]
Please check in these sets of foliage (trees, crops, flowers, etc.) organized into folder for each of the "areas" of 1660 Manhattan, per the Castello Plan map (and Stokes Key).  Like 1660_A, etc.

![Image](https://github.com/user-attachments/assets/193bc5c4-3cf3-4e51-a4b7-3c3c959fcdfa)

**Comment by tedbarnett** [comment]
@KatherineMcDonnell Although no detailed plans for the crop placement in the Castello Plan may be availalbe, we need to generate a "working assumptions" plan of that placement to guide @tantayota as he places the orchards and crops.  Please make a keyed (color-coded?) Castello Plan overlay map that Alvin can use to define what trees and crop types are to be placed on the terrain.  Use the same Castello Plan JPG or PNG file resolution as we now have in the project to ensure they can be lined up.

**Comment by tedbarnett** [comment]
Re: adding notes from old Issue #187 "Identify 1660 Castello Plan Crop Placements" here...
For 1664, in addition to knowing “what was the terrain like from Wall Street to 59th Street (north of the Castello Plan map)?”, we need to guess exactly what the plant types are on this Castello Plan map. 1) Which crops are wheat, barley, rye, corn, tobacco? 2) Which orchards are apple, cherry, peach, pear? 3) What vegetables are growing in the gardens?

Even if no data is available, come up with a placeholder assumptions map we can use for layout (and later edit/correct if more information does become available).  That map should take into account:

1. Items as they appear on the Castello Plan (i.e. "are they orchards vs. crops vs. gardens?", "what type of plant do they appear to be?")
2. The likely distribution of these kinds of crops/orchards/vegetables below the Wall as of 1660?  Look for likely food requirements for a colony of this size (1000 people), and data from analogous colonies in the same time period (what did they grow)

We can't be precise since data is sorely lacking, but we can make an educated starting plan and edit it later.

**Comment by tedbarnett** [comment]
Almost done!
![Image](https://github.com/user-attachments/assets/66a2cde7-fd29-43aa-9c34-b95b01534a03)
