### ISSUE TITLE
Set World time to September 11, 1609 at 9:00am

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#7]
September 11, 1609 at 9:00am seems likely the date and time when Henry Hudson's ship The Half Moon" first approached Manhattan.  (source: https://www.loc.gov/resource/gdclccn.11022268/?sp=9).  So...
- Set sun altitude and direction per NOAA data below

![1609 Sunrise and sunset](https://github.com/TimeWalkOrg/Manhattan/assets/694013/d15cf9dc-07e4-445c-91f0-dee29d1f60ed)

**Comment by tedbarnett** [comment]
could we set the date/time to September 3, 1609 at 9:00am (ET)?  Learned that is a more accurate estimate per this ChatGPT conversation: https://chat.openai.com/share/3c5798cb-3a3d-4c96-985c-c7ffadb4ff0a

**Comment by tedbarnett** [comment]
I see that you have some code controlling this, but I wasn't sure where to change the Day Value for this model

**Comment by deedox** [comment]
The Sun and Sky works with latitude/longitude values.. Year setup is now working yet only month and day.

**Comment by tedbarnett** [comment]
So cool!
