### ISSUE TITLE
Elm Trees wrong resolution (LOD issue?)

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#78]
The American Elm needs to be replaced with a model that works with our system.  Elms are important trees (e.g. Peter Minuit met the Lenape under one), so worth having working copies.  Tried turning Nanite on/off to no avail.

![Image](https://github.com/user-attachments/assets/69b629e6-5402-435a-80e1-4755f5a65871)

**Comment by deedox** [comment]
a compression issue.. easy to fix

**Comment by tedbarnett** [comment]
Fixed!
