### ISSUE TITLE
Add back reference Labels and "Ghost" buildings ("L")

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#80]
Pressing the "L" key should toggle text labels (area and street names) and "ghost" buildings (Brooklyn Bridge, One World Trade Center, Trinity Church).

**Comment by deedox** [comment]
The labels are now a sublebel and they work, but only within the Persistent Level...

**Comment by tedbarnett** [comment]
Nice.  I edited the sublevel and took out the non-ghost building models (made them not visible)
