### ISSUE TITLE
Darkened area of ocean water

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#84]
Looks like some Ocean/water setting is changing the color (or reflectivity) of the ocean water.  See 1664 harbor area:

![Image](https://github.com/user-attachments/assets/423c570d-66c8-4479-9625-69861cabc7cd)

**Comment by deedox** [comment]
Hmm, seems to be an issue on your PC, for me everything looks good. Water is still WIP so more updates will  come later including real geometry coastal waves..

**Comment by tedbarnett** [comment]
Looks fixed on my PC now
