### ISSUE TITLE
Bug: floating orchard trees

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#98]
Orchard trees seem to be on the wrong landscape in 1664.  Might be that it's conforming to Dario's new 12K BC terrain?

![Image](https://github.com/user-attachments/assets/412604c9-f7cc-4855-b8f2-5cc9aab8da93)

**Comment by deedox** [comment]
Ahh yes forgot to turn off the level blocking on 1609 when invisible.. Takes 3mins to fix
